---
# copyright Utrecht University

- name: Ensure PostgreSQL database and dependencies are installed
  ansible.builtin.package:
    name:
      - "postgresql{{ pgsql_version }}-server"
      - "postgresql{{ pgsql_version }}-contrib"
    state: present
  when: not ansible_check_mode


- name: Ensure PsycoPG2 is installed
  ansible.builtin.package:
    name: python3-psycopg2
    state: present
  when: not ansible_check_mode
