---
# copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


- name: Install Anubis (EL)
  ansible.builtin.import_tasks: install-redhat.yml
  when: enable_anubis and ansible_os_family == 'RedHat'


- name: Install Anubis (Ubuntu)
  ansible.builtin.import_tasks: install-ubuntu.yml
  when: enable_anubis and ansible_os_family == 'Debian'


- name: Generate key for Redis persist after restart for Anubis
  ansible.builtin.command: 'openssl rand -hex 32'
  register: priv_key
  args:
    creates: "{{ anubis_redis_priv_key_path }}"
  when: enable_anubis


- name: Store Anubis key in variable
  ansible.builtin.set_fact:
    '{{ item.fact }}': '{{ item.key }}'
  with_items:
    - fact: anubis_redis_priv_key
      key: '{{ priv_key.stdout }}'
  when: enable_anubis and not ansible_check_mode


- name: Check if Anubis key file exists
  ansible.builtin.stat:
    path: '{{ anubis_redis_priv_key_path }}'
  ignore_errors: true
  register: anubis_key_exists
  when: enable_anubis


- name: Save key in file
  ansible.builtin.copy:
    content: '{{ anubis_redis_priv_key }}'
    dest: '{{ anubis_redis_priv_key_path }}'
    mode: '0644'
  when: enable_anubis and not anubis_key_exists.stat.exists and not ansible_check_mode


- name: Ensure Anubis env file is present for DavRods
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/etc/anubis/{{ item }}'
    mode: '0644'
  notify: Restart Anubis
  with_items:
    - davrods.env
  when: enable_anubis and ((yoda_davrods_anonymous_enabled is not defined) or yoda_davrods_anonymous_enabled)


- name: Ensure Anubis env file is present for landing pages
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/etc/anubis/{{ item }}'
    mode: '0644'
  notify: Restart Anubis
  with_items:
    - landingpages.env
  when: enable_anubis


- name: Ensure Anubis bot policies file is present
  ansible.builtin.template:
    src: yoda.botPolicies.yaml.j2
    dest: /etc/anubis/yoda.botPolicies.yaml
    mode: '0644'
  notify: Restart Anubis
  when: enable_anubis


- name: Ensure Apache modules for Anubis are enabled (Ubuntu)
  ansible.builtin.file:
    src: "{{ apache_module_config_dir }}/{{ item }}.load"
    dest: "{{ apache_module_enabled_config_dir }}/{{ item }}.load"
    state: link
  notify: Restart Apache webserver
  with_items:
    - "headers"
    - "proxy"
    - "proxy_http"
    - "rewrite"
    - "substitute"
  when: ansible_os_family == 'Debian' and enable_anubis


- name: Allow Anubis to listen on ports for DavRods
  community.general.seport:
    ports: '{{ item }}'
    proto: tcp
    setype: http_port_t
    state: present
  notify: Restart Anubis
  with_items:
    - '{{ anubis_davrods_bind_port }}'
  when: ansible_os_family == 'RedHat' and enable_anubis and ansible_selinux.status == "enabled" and ((yoda_davrods_anonymous_enabled is not defined) or yoda_davrods_anonymous_enabled)


- name: Allow Anubis to listen on ports for the landing pages
  community.general.seport:
    ports: '{{ item }}'
    proto: tcp
    setype: http_port_t
    state: present
  notify: Restart Anubis
  with_items:
    - '{{ anubis_landingpages_bind_port }}'
  when: ansible_os_family == 'RedHat' and enable_anubis and ansible_selinux.status == "enabled"


- name: Ensure Anubis is running and enabled for Davrods
  ansible.builtin.service:
    name: anubis@davrods.service
    state: started
    enabled: true
  when: enable_anubis and ((yoda_davrods_anonymous_enabled is not defined) or yoda_davrods_anonymous_enabled)


- name: Ensure Anubis is running and enabled for landing pages
  ansible.builtin.service:
    name: anubis@landingpages.service
    state: started
    enabled: true
  when: enable_anubis


- name: Ensure Anubis is disabled
  ansible.builtin.service:
    name: 'anubis@{{ item }}.service'
    state: stopped
    enabled: false
  when: not enable_anubis
  with_items:
    - davrods
    - landingpages
  ignore_errors: true
  register: ignore_errors_anubis


- name: Copy Anubis listener configuration (Ubuntu)
  when: enable_anubis and ansible_os_family == 'Debian'
  ansible.builtin.template:
    src: listener.conf.j2
    dest: "{{ apache_conf_avail_dir }}/{{ anubis_listener_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache webserver


- name: Copy Anubis listener configuration (EL)
  when: enable_anubis and ansible_os_family == 'RedHat'
  ansible.builtin.template:
    src: listener.conf.j2
    dest: "{{ apache_site_config_dir }}/{{ anubis_listener_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache webserver


- name: Ensure apache listener config for Anubis is enabled (Ubuntu)
  ansible.builtin.file:
    src: "{{ apache_conf_avail_dir }}//{{ item }}"
    dest: "{{ apache_enabled_config_dir }}//{{ item }}"
    state: link
  notify: Restart Apache webserver
  with_items:
    - "{{ anubis_listener_config_file }}"
  when: enable_anubis and ansible_os_family == 'Debian'


- name: Ensure Anubis static directory for Yoda images is present
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: '{{ yoda_davrods_user }}'
    group: '{{ yoda_davrods_group }}'
  with_items:
    - '{{ anubis_yoda_static }}'
    - '{{ anubis_yoda_static }}/img/'
  when: enable_anubis


- name: Ensure static files for Yoda theme for Anubis are present
  ansible.builtin.copy:
    src: yoda.webp
    dest: '{{ anubis_yoda_static }}/img/yoda.webp'
    owner: '{{ yoda_davrods_user }}'
    group: '{{ yoda_davrods_group }}'
    mode: '0644'
  when: enable_anubis
