---
# copyright Utrecht University

- name: Restart Postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: not ansible_check_mode


- name: Reload Apparmor
  ansible.builtin.service:
    name: apparmor
    state: reloaded


- name: Systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true


- name: Load Postfix Canonical Map
  ansible.builtin.command: # noqa no-changed-when
    cmd: postmap canonical
    chdir: /etc/postfix
  when: not ansible_check_mode
