---
# copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


- name: Ensure pam_radius is absent
  ansible.builtin.package:
    name: '{{ pam_radius_package }}'
    state: absent


- name: Ensure deprecated RADIUS fallback is not  is configured
  ansible.builtin.file:
    path: /etc/pam_radius.conf
    state: absent


- name: Ensure external user check is present
  ansible.builtin.template:
    src: is-user-external.sh.j2
    dest: /usr/local/bin/is-user-external.sh
    owner: root
    group: "{{ irods_service_account }}"
    mode: '0750'
  when: external_users


- name: Ensure external user authentication is present
  ansible.builtin.template:
    src: external-auth.py.j2
    dest: /usr/local/bin/external-auth.py
    owner: root
    group: "{{ irods_service_account }}"
    mode: '0750'
  no_log: true
  when: external_users


- name: Ensure sqlcipher3 virtualenv exists
  become_user: "{{ irods_service_account }}"
  become: true
  ansible.builtin.command: "python3 -m venv /var/lib/irods/sqlcipher3-venv"
  args:
    creates: /var/lib/irods/sqlcipher3-venv


# When data access tokens are enabled, sqlcipher3-binary needs to be
# installed in a venv too for the token authentication script
# (in addition to the user-level installation for the ruleset).
- name: Ensure pysqlcipher3 is installed for token authentication script
  become_user: "{{ irods_service_account }}"
  become: true
  ansible.builtin.pip:
    name: sqlcipher3-binary==0.5.4
    executable: /var/lib/irods/sqlcipher3-venv/bin/pip3
    state: present


- name: Ensure token authentication script is present
  ansible.builtin.template:
    src: token-auth.py.j2
    dest: /usr/local/bin/token-auth.py
    owner: root
    group: "{{ irods_service_account }}"
    mode: '0750'
  no_log: true
  when: enable_tokens


- name: Ensure /etc/pam.d/irods is configured
  ansible.builtin.template:
    src: 'irods_pam.j2'
    dest: '/etc/pam.d/irods'
    mode: '0644'


- name: Ensure OIDC authentication is present
  become_user: '{{ irods_service_account }}'
  become: true
  when: oidc_active is defined and oidc_active is sameas true
  ansible.builtin.template:
    src: oidc.py.j2
    dest: /var/lib/irods/msiExecCmd_bin/oidc.py
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0644'


- name: Ensure correct file ownership and mode on PamAuthCheck
  ansible.builtin.file:
    path: /usr/sbin/irodsPamAuthCheck
    owner: root
    group: root
    mode: '04755'
  when: not ansible_check_mode
