---
# copyright Utrecht University

# Zabbix agent rpm location and checksum
zabbix_agent:
  package: zabbix-agent2-7.4.5
  url: https://repo.zabbix.com/zabbix/7.4/stable/rhel/8/x86_64
  filename: zabbix-agent2-7.4.5-release2.el8.x86_64.rpm
  checksum: sha256:f1e864322ae624603f1409e11b1dc03b32c937c936ba4bb54e739801544bc49e
  rpm_key_loc: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-B5333005
