---
# copyright Utrecht University

- name: Check whether Zabbix agent2 PostgreSQL plugin has been installed
  ansible.builtin.command:
    cmd: "dpkg-query -W --showformat='${Status}\n' {{ zabbix_agent2_postgresql_plugin.package }}"
  register: zabbix_psqlplugin_current_package_status
  failed_when: zabbix_psqlplugin_current_package_status.rc not in [0, 1]
  changed_when: false


- name: Check current Zabbix agent2 PostgreSQL plugin version
  ansible.builtin.command:
    cmd: "dpkg-query -W --showformat='${Version}\n' {{ zabbix_agent2_postgresql_plugin.package }}"
  register: zabbix_psqlplugin_current_package_version
  changed_when: false
  failed_when: zabbix_psqlplugin_current_package_version.rc not in [0, 1]


- name: Download Zabbix agent2 PostgreSQL plugin package
  ansible.builtin.get_url:
    url: '{{ zabbix_agent2_postgresql_plugin.url }}/{{ zabbix_agent2_postgresql_plugin.filename }}'
    dest: '{{ yoda_zabbix_package_dir }}/{{ zabbix_agent2_postgresql_plugin.filename }}'
    checksum: '{{ zabbix_agent2_postgresql_plugin.checksum }}'
    mode: '0644'
  when: not ansible_check_mode and ('install ok installed' not in zabbix_psqlplugin_current_package_status.stdout or zabbix_psqlplugin_current_package_version.stdout != zabbix_agent2_postgresql_plugin.package_version)


- name: Install Zabbix agent2 PostgreSQL plugin from package
  ansible.builtin.apt:
    deb: '{{ yoda_zabbix_package_dir }}/{{ zabbix_agent2_postgresql_plugin.filename }}'
    state: present
  when: not ansible_check_mode and ('install ok installed' not in zabbix_psqlplugin_current_package_status.stdout or zabbix_psqlplugin_current_package_version.stdout != zabbix_agent2_postgresql_plugin.package_version)
