---
# copyright Utrecht University

- name: Include distribution version specific variables for Zabbix (EL)
  ansible.builtin.include_vars: "rh{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == 'RedHat'


- name: Include distribution version specific variables for Zabbix (Ubuntu)
  ansible.builtin.include_vars: "ubuntu.yml"
  when: ansible_os_family == 'Debian'


- name: Create Zabbix database user
  become_user: postgres
  become: true
  community.postgresql.postgresql_user:
    name: "{{ zabbix_database_user }}"
    password: "{{ zabbix_database_user_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE


- name: Grant pg_monitor role to Zabbix user
  become_user: postgres
  become: true
  community.postgresql.postgresql_membership:
    group: pg_monitor
    target_roles:
      - "{{ zabbix_database_user }}"
    state: present


- name: Remove old libzbxpgsql plugin
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/zabbix/zabbix_agentd.d/libzbxpgsql.conf"
    - "/usr/lib64/zabbix/modules/libzbxpgsql.so"


- name: Install Zabbix-agent2 PostgreSQL plugin package for Debian family
  ansible.builtin.include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'


- name: Install Zabbix-agent2 PostgreSQL plugin package for RedHat family
  ansible.builtin.include_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'
