---
# copyright Utrecht University

# GCC is needed to install pysqlcipher3 for yoda-ruleset
- name: Ensure Python dependencies are installed
  ansible.builtin.package:
    name: gcc
    state: present


- name: Ensure SQLCipher packages are installed
  ansible.builtin.package:
    name:
      - sqlcipher
      - sqlcipher-devel
    state: present
  when: ansible_os_family == 'RedHat'


- name: Ensure SQLCipher packages are installed
  ansible.builtin.package:
    name:
      - sqlcipher
      - libsqlcipher1
      - libsqlcipher-dev
    state: present
  when: ansible_os_family == 'Debian'
