---
# copyright Utrecht University

irods_service_account: irods

irods_enable_gocommands: false
irods_gocommands_version: 0.10.8
irods_gocommands_archive_checksum: "sha256:43f80da3f1901239eed7c360b328e57a54b9c287f1a7d960a10a988078827542"
