---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 10.1.0
  - name: community.crypto
    version: 2.25.0
  - name: community.postgresql
    version: 3.9.0
