$umask 0000
$WorkDirectory /var/lib/irods-log
$FileOwner syslog
$FileGroup syslog
$FileCreateMode 0644
$DirCreateMode 0755

module(load="omprog")

if (re_match($programname, "^irods(Server|DelayServer|Agent)")) then {
    action(type="omprog" name="transformer" binary="/usr/local/bin/irods-log-transform.py")
    stop
}
