$umask 0000
$WorkDirectory /var/lib/irods-log
$FileOwner syslog
$FileGroup syslog
$FileCreateMode 0644
$DirCreateMode 0755

module(load="omprog")

if ($programname == 'irodsServer' or $programname == "irodsReServer") then {
	action(type="omprog" name="transformer" binary="/usr/local/sbin/irods-log-transform.py")
	stop
}
