---
# copyright Utrecht University

- name: Restart Redis
  ansible.builtin.service:
    name: 'redis-server-{{ redis_port }}'
    state: restarted
  when: not ansible_check_mode


- name: Systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
