---
# copyright Utrecht University

- name: Restart Redis
  ansible.builtin.service:
    name: 'redis-server-{{ redis_port }}'
    state: restarted


- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
