---
# copyright Utrecht University

- name: Restart Redis
  ansible.builtin.service:
    name: redis
    state: started


- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
