---
# copyright Utrecht University

# Latest stable version of Anubis: https://github.com/TecharoHQ/anubis/releases
anubis_deb_url: https://github.com/TecharoHQ/anubis/releases/download/v1.23.1/anubis_1.23.1_amd64.deb
anubis_deb_checksum: sha256:8947f969c770e85ad23da253ffa73e5ec47ecd55cb0c4fbb1f9928aa81ac490f
yoda_davrods_user: www-data
yoda_davrods_group: www-data
