---
# copyright Utrecht University

# Latest stable version of Anubis: https://github.com/TecharoHQ/anubis/releases
anubis_rpm_url: https://github.com/TecharoHQ/anubis/releases/download/v1.23.1/anubis-1.23.1-1.x86_64.rpm
anubis_rpm_checksum: sha256:9966fad368757dac80bf7fed0539ff20f07ed8a2c6210ac38b36c55d6a89f39c
yoda_davrods_user: apache
yoda_davrods_group: apache
