---
# copyright Utrecht University

- name: Run s3cmd tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_s3cmd_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that s3cmd role has run
  ansible.builtin.set_fact:
    yoda_s3cmd_role_has_run: true
  when: '"yoda_s3cmd_role_has_run" not in hostvars[inventory_hostname]'
