---
# copyright Utrecht University

- name: Run postgresql_repository tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_postgresql_repository_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that postgresql_repository role has run
  ansible.builtin.set_fact:
    yoda_postgresql_repository_role_has_run: true
  when: '"yoda_postgresql_repository_role_has_run" not in hostvars[inventory_hostname]'
