---
# copyright Utrecht University

- name: Ensure PostgreSQL APT signing key is present
  ansible.builtin.apt_key:
    url: "{{ postgresql_apt_signing_key }}"
    state: present


- name: Ensure PostgreSQL packages APT repository is enabled
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    filename: pgdg
    state: present
  with_items:
    - "{{ postgresql_apt_repo }}"
    - "{{ postgresql_apt_archive_repo }}"
