---
# copyright Utrecht University

openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'

apache_service_name: httpd

yoda_davrods_boost_package: boost
yoda_davrods_jansson_package: jansson

yoda_davrods_url: https://github.com/UtrechtUniversity/davrods/releases/download/4.3.4_1.5.3/davrods-4.3.4_1.5.3-1.rpm
yoda_davrods_version: 4.3.4-1.5.3
yoda_davrods_checksum: sha256:1b8cdd067202ffb34b0f5634b03969b5f1d8d12a839ba203219727f890c77752

yoda_davrods_site_config_dir: /etc/httpd/conf.d
yoda_davrods_config_file: davrods-vhost.conf
yoda_davrods_anon_config_file: davrods-anonymous-vhost.conf
yoda_davrods_apache_log_dir: /var/log/httpd
yoda_davrods_irods_dir: /etc/httpd/irods
yoda_davrods_config_dir: /etc/httpd/irods
yoda_davrods_user: apache
yoda_davrods_group: apache
