---
# copyright Utrecht University

openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'

yoda_davrods_boost_package: boost
yoda_davrods_jansson_package: jansson

yoda_davrods_url: https://github.com/UtrechtUniversity/davrods/releases/download/4.3.4_1.5.1/davrods-4.3.4_1.5.1-1.rpm
yoda_davrods_version: 4.3.4-1.5.1
yoda_davrods_checksum: sha256:2a59b839b314697c03b308f47a6b4fd8ef956bfa57a2af412f3ca5a4f4c58bf3

yoda_davrods_site_config_dir: /etc/httpd/conf.d
yoda_davrods_config_file: davrods-vhost.conf
yoda_davrods_anon_config_file: davrods-anonymous-vhost.conf
yoda_davrods_apache_log_dir: /var/log/httpd
yoda_davrods_irods_dir: /etc/httpd/irods
yoda_davrods_config_dir: /etc/httpd/irods
yoda_davrods_user: apache
yoda_davrods_group: apache
