---
# copyright Utrecht University

openssl_private_dir: '/etc/pki/tls/private'
openssl_certs_dir: '/etc/pki/tls/certs'

apache_service_name: httpd

yoda_davrods_boost_package: boost
yoda_davrods_jansson_package: jansson

yoda_davrods_url: https://github.com/UtrechtUniversity/davrods/releases/download/5.0.2_1.5.4/davrods-5.0.2_1.5.4-1.rpm
yoda_davrods_version: 5.0.2-1.5.4
yoda_davrods_checksum: sha256:943111a8e7578a1c0a9b2d0de61dabb46f0de98947610943944ce5ed77209646

yoda_davrods_site_config_dir: /etc/httpd/conf.d
yoda_davrods_config_file: davrods-vhost.conf
yoda_davrods_anon_config_file: davrods-anonymous-vhost.conf
yoda_davrods_anon_anubis_listener_config_file: davrods-anubis-listener.conf
yoda_davrods_apache_log_dir: /var/log/httpd
yoda_davrods_irods_dir: /etc/httpd/irods
yoda_davrods_config_dir: /etc/httpd/irods
yoda_davrods_user: apache
yoda_davrods_group: apache
