---
# copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


- name: Ensure iCAT database checker virtualenv exists
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.command: "{{ icat_database_checker_python3_path }} -m venv /var/lib/irods/icat-database-checker"
  args:
    creates: /var/lib/irods/icat-database-checker


- name: Ensure iCAT database checker is installed
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.pip:
    name: "git+https://github.com/UtrechtUniversity/icat-database-checker.git@v{{ icat_database_checker_version }}"
    virtualenv: '/var/lib/irods/icat-database-checker'
    virtualenv_python: python3
