---
# copyright Utrecht University

- name: Run yoda_zabbix_system tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_yoda_zabbix_system_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that yoda_zabbix_system role has run
  ansible.builtin.set_fact:
    yoda_yoda_zabbix_system_role_has_run: true
  when: '"yoda_yoda_zabbix_system_role_has_run" not in hostvars[inventory_hostname]'
