---
# copyright Utrecht University

openssl_private_dir: '/etc/ssl/private/'
openssl_certs_dir: '/etc/ssl/certs'

pam_radius_package: libpam-radius-auth

irods_runtime_package_new: irods-runtime=5.0.2-0~noble
irods_server_package_new: irods-server=5.0.2-0~noble
irods_prep_package_new: irods-rule-engine-plugin-python=5.0.1-0+5.0.2~noble
irods_pgp_package_new: irods-database-plugin-postgres=5.0.2-0~noble
irods_idp_package_new: irods-rule-engine-plugin-indexing=5.0.1-0+5.0.2~noble
irods_esp_package_new: irods-rule-engine-plugin-elasticsearch=5.0.1-0+5.0.2~noble

sqlcipher3_venv_path: /var/lib/irods/sqlcipher3-venv/lib64/python3.12/site-packages/
