---
# copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


- name: Determine the SANs this host's certificate must cover
  ansible.builtin.include_tasks: san-names.yml


- name: Install pinned Certbot in a virtual environment
  ansible.builtin.include_tasks: install_certbot.yml


- name: Check if certificate already exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ yoda_portal_fqdn }}/fullchain.pem"
  register: letsencrypt_fullchain


- name: Determine whether a certificate must be requested
  ansible.builtin.set_fact:
    acme_certificates_must_issue: "{{ acme_certificates_issue_certificate | bool and not letsencrypt_fullchain.stat.exists }}"


- name: Ensure Apache is stopped
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: stopped
  when: acme_certificates_must_issue


- name: Generate certificate if it  doesn't exist yet # noqa no-changed-when
  ansible.builtin.command: "certbot certonly --standalone --noninteractive --agree-tos --email {{ acme_certificates_email_contact }} -d {{ acme_certificates_san_names | join(' -d ') }}"
  when: acme_certificates_must_issue


- name: Ensure Apache is started
  ansible.builtin.service:
    name: "{{ apache_service_name }}"
    state: started
  when: acme_certificates_must_issue


- name: Install the certificate deploy hook
  ansible.builtin.template:
    src: renew-deploy-hook.sh.j2
    dest: "{{ acme_certificates_deploy_hook }}"
    owner: root
    group: root
    mode: '0750'


- name: Add cronjob for Certbot renewal
  ansible.builtin.cron:
    name: Certbot automatic renewal
    job: "sudo certbot renew --quiet --pre-hook 'systemctl stop {{ apache_service_name }}' --post-hook 'systemctl start {{ apache_service_name }}' --deploy-hook {{ acme_certificates_deploy_hook }}"
    minute: 25
    hour: 0,12
  when: acme_certificates_issue_certificate | bool


- name: Ensure new certificate is used
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
    remote_src: true
  with_items:
    - src: '/etc/letsencrypt/live/{{ yoda_portal_fqdn }}/fullchain.pem'
      dest: '{{ openssl_certs_dir }}/localhost_and_chain.crt'
      mode: '0644'
    - src: '/etc/letsencrypt/live/{{ yoda_portal_fqdn }}/fullchain.pem'
      dest: '{{ openssl_certs_dir }}/localhost.crt'
      mode: '0644'
    - src: '/etc/letsencrypt/live/{{ yoda_portal_fqdn }}/privkey.pem'
      dest: '{{ openssl_private_dir }}/localhost.key'
      mode: '0600'
  when:
    - acme_certificates_issue_certificate | bool
    - not ansible_check_mode
