---
# copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


# TODO install in venv
- name: Ensure python-irodsclient is installed (Python 3)
  ansible.builtin.pip:
    name: "python_irodsclient=={{ python_irodsclient_version }}"
    executable: "{{ python_irodsclient_pip3_path }}"
    extra_args: "--break-system-packages"
  when: not ansible_check_mode
