---
# copyright Utrecht University

- name: Ensure PostgreSQL ODBC dependencies are installed
  ansible.builtin.package:
    name:
      - "postgresql{{ pgsql_version }}-odbc"
      - unixODBC
    state: present
  when: not ansible_check_mode
