# Copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


- name: Set correct permissions for certificate chain
  ansible.builtin.file:
    path: '{{ openssl_certs_dir }}/{{ openssl_chain }}'
    mode: '0640'
    group: 'irods'
    owner: 'root'
    state: file


- name: Configure cronjob to update resource storage data
  become_user: "{{ irods_service_account }}"
  become: true
  ansible.builtin.cron:
    name: 'arb-update-resources.py'
    minute: '*'
    hour: '*'
    job: '/usr/bin/python3 /etc/irods/yoda-ruleset/tools/arb-update-resources.py > /dev/null'
    state: '{{ "present" if irods_arb_enabled else "absent" }}'


- name: Ensure psutil is installed
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.pip:
    name: "psutil==5.9.5"
    executable: "{{ irods_arb_pip3_location }}"
    extra_args: --user --break-system-packages
  when: ansible_os_family == 'Debian'


- name: Ensure psutil is installed
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.pip:
    name: "psutil==5.9.5"
    executable: "{{ irods_arb_pip3_location }}"
  when: ansible_os_family == 'RedHat'
