---
# copyright Utrecht University


irods_service_account: irods
yoda_clienttools_repo: "https://github.com/UtrechtUniversity/yoda-clienttools"
yoda_clienttools_version: "2.3.1"
yoda_clienttools_path: "/var/lib/irods/yoda-clienttools"
