---
# copyright Utrecht University

# Anubis configuration
enable_anubis: false                # Enable Anubis
anubis_yoda_static: /etc/anubis/static-yoda
anubis_davrods_bind_port: 8923
anubis_landingpages_bind_port: 8924
anubis_davrods_port: 3001
anubis_landingpages_port: 3002
anubis_redis_priv_key_path: '/etc/anubis/anubis-redis.key'

yoda_davrods_anonymous_enabled: true
