---
# copyright Utrecht University

- name: Run certificates tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_certificates_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that certificates role has run
  ansible.builtin.set_fact:
    yoda_certificates_role_has_run: true
  when: '"yoda_certificates_role_has_run" not in hostvars[inventory_hostname]'
