---
# copyright Utrecht University

- name: Run python3 tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_python3_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that python3 role has run
  ansible.builtin.set_fact:
    yoda_python3_role_has_run: true
  when: '"yoda_python3_role_has_run" not in hostvars[inventory_hostname]'
