---
# copyright Utrecht University

nfs_mounts:

# Example configuration for development environment.
# nfs_mounts:
#  - host: combined.yoda.test
#    src: "{{ ansible_host }}:/var/nfs/Vault1_1"
#    path: "/nfs/Vault1_1"
#  - host: combined.yoda.test
#    src: "{{ ansible_host }}:/var/nfs/Vault1_2"
#    path: "/nfs/Vault1_2"
#  - host: combined.yoda.test
#    src: "{{ ansible_host }}:/var/nfs/Vault2_1"
#    path: "/nfs/Vault2_1"
