---
# copyright Utrecht University

- name: Install yoda reporting private key
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.template:
    src: yoda_report.j2
    dest: '{{ yoda_report_server_priv_key_loc }}'
    owner: '{{ irods_service_account }}'
    mode: '0600'
  when: enable_yoda_report and yoda_report_upload_priv_key is defined


- name: Scan yoda reporting server host pub key # noqa no-changed-when
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.shell: "ssh-keyscan {{ yoda_report_server_host }} >> ~/.ssh/known_hosts"
  when: enable_yoda_report and yoda_report_upload_priv_key is defined


- name: Create directory /var/yoda-financial-data
  ansible.builtin.file:
    path: /var/yoda-financial-data
    state: directory
    mode: '0700'
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
  when: enable_yoda_report


- name: Ensure correct ownership and permissions for /var/yoda-financial-data
  ansible.builtin.file:
    path: /var/yoda-financial-data
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0700'
  when: enable_yoda_report


- name: Copy file to remote /var directory
  ansible.builtin.copy:
    src: gather-group-statistics.py
    dest: /var/yoda-financial-data/gather-group-statistics.py
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0700'
  when: enable_yoda_report


- name: Copy file to remote /var directory
  ansible.builtin.copy:
    src: requirements.txt
    dest: /var/yoda-financial-data/requirements.txt
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0700'
  when: enable_yoda_report


- name: Create a Python virtual environment
  ansible.builtin.command:
    cmd: "python3 -m venv /var/yoda-financial-data/yoda_report_venv"
    creates: "/var/yoda-financial-data/yoda_report_venv"
  when: enable_yoda_report


- name: Install requirements in the virtual environment # noqa no-changed-when
  ansible.builtin.shell: >
    source /var/yoda-financial-data/yoda_report_venv/bin/activate &&
    pip install -r /var/yoda-financial-data/requirements.txt
  args:
    executable: /bin/bash
  when: enable_yoda_report


- name: Add cron job to gather financial group statistics
  ansible.builtin.cron:
    name: "yoda-report-gather-group-statistics"
    minute: 0
    hour: 1
    job: >
      source /var/yoda-financial-data/yoda_report_venv/bin/activate &&
      python /var/yoda-financial-data/gather-group-statistics.py
    user: "{{ irods_service_account }}"
    state: "{{ 'present' if enable_yoda_report else 'absent' }}"


- name: Add cron job to transfer financial group statistics to reporting server
  ansible.builtin.cron:
    name: "yoda-report-copy-group-statistics"
    minute: 0
    hour: 3
    job: >
      source /var/yoda-financial-data/yoda_report_venv/bin/activate &&
      scp -i {{ yoda_report_server_priv_key_loc }}
      /var/yoda-financial-data/stats.yaml
      {{ yoda_report_server_user_account }}@{{ yoda_report_server_host }}:{{ yoda_report_server_dir }}/{{ instance }}.stats.yml
    user: "{{ irods_service_account }}"
    state: "{{ 'present' if enable_yoda_report else 'absent' }}"
