---
# copyright Utrecht University

- name: Install yoda reporting private key
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.template:
    src: yoda_report.j2
    dest: '{{ yoda_report_server_priv_key_loc }}'
    owner: '{{ irods_service_account }}'
    mode: '0600'
  no_log: true
  when: enable_yoda_report and yoda_report_upload_priv_key is defined


- name: Scan yoda reporting server host pub key # noqa no-changed-when
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.shell: "ssh-keyscan {{ yoda_report_server_host }} >> ~/.ssh/known_hosts"
  when: enable_yoda_report and yoda_report_upload_priv_key is defined


- name: Create directory /var/yoda-financial-data
  ansible.builtin.file:
    path: /var/yoda-financial-data
    state: directory
    mode: '0700'
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
  when: enable_yoda_report


- name: Ensure correct ownership and permissions for /var/yoda-financial-data
  ansible.builtin.file:
    path: /var/yoda-financial-data
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0700'
  when: enable_yoda_report


- name: Remove gather group stats script from remote /var directory
  ansible.builtin.file:
    path: /var/yoda-financial-data/gather-group-statistics.py
    state: absent
  when: enable_yoda_report


- name: Copy file for gathering and sending group stats to remote /var directory
  ansible.builtin.copy:
    src: gather-group-stats.sh
    dest: /var/yoda-financial-data/gather-group-stats.sh
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0700'
  when: enable_yoda_report


- name: Copy file for gathering capacity stats to remote /var directory
  ansible.builtin.copy:
    src: gather-capacity-stats.py
    dest: /var/yoda-financial-data/gather-capacity-stats.py
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0700'
  when: enable_yoda_report


- name: Copy file to remote /var directory
  ansible.builtin.copy:
    src: requirements.txt
    dest: /var/yoda-financial-data/requirements.txt
    owner: "{{ irods_service_account }}"
    group: "{{ irods_service_account }}"
    mode: '0700'
  when: enable_yoda_report


- name: Create a Python virtual environment
  ansible.builtin.command:
    cmd: "python3 -m venv /var/yoda-financial-data/yoda_report_venv"
    creates: "/var/yoda-financial-data/yoda_report_venv"
  when: enable_yoda_report


- name: Install requirements in the virtual environment # noqa no-changed-when
  ansible.builtin.shell: >
    source /var/yoda-financial-data/yoda_report_venv/bin/activate &&
    pip install -r /var/yoda-financial-data/requirements.txt
  args:
    executable: /bin/bash
  when: enable_yoda_report


- name: Remove cron job for gathering financial group statistics
  ansible.builtin.cron:
    name: "yoda-report-gather-group-statistics"
    user: "{{ irods_service_account }}"
    state: absent
  when: inventory_hostname in groups['icats']


- name: Gather and transfer group stats for billing (weekly)
  ansible.builtin.cron:
    name: "yoda-report-gather-and-send-group-stats"
    minute: 0
    hour: 1
    weekday: 6
    user: "{{ irods_service_account }}"
    job: >
      INSTANCE="{{ instance }}"
      YODA_REPORT_SERVER_PRIV_KEY_LOC="{{ yoda_report_server_priv_key_loc }}"
      YODA_REPORT_SERVER_USER_ACCOUNT="{{ yoda_report_server_user_account }}"
      YODA_REPORT_SERVER_HOST="{{ yoda_report_server_host }}"
      YODA_REPORT_SERVER_FINANCIAL_DATA_DIR="{{ yoda_report_server_financial_data_dir }}"
      /bin/bash /var/yoda-financial-data/gather-group-stats.sh
    state: "{{ 'present' if enable_yoda_report else 'absent' }}"
  when: inventory_hostname in groups['icats']


- name: Add cron job to gather capacity statistics
  ansible.builtin.cron:
    name: "yoda-report-gather-capacity-statistics"
    minute: 0
    hour: 1
    job: /var/yoda-financial-data/yoda_report_venv/bin/python /var/yoda-financial-data/gather-capacity-stats.py
    user: "{{ irods_service_account }}"
    state: "{{ 'present' if enable_yoda_report else 'absent' }}"


- name: Add cron job to transfer capacity statistics to reporting server
  ansible.builtin.cron:
    name: "yoda-report-copy-capacity-statistics"
    minute: 0
    hour: 3
    job: >
      scp -i {{ yoda_report_server_priv_key_loc }}
      /var/yoda-financial-data/*.capacity.yaml
      {{ yoda_report_server_user_account }}@{{ yoda_report_server_host }}:{{ yoda_report_server_capacity_data_dir }}/{{ inventory_hostname.split('.')[0] }}.capacity.yaml
    user: "{{ irods_service_account }}"
    state: "{{ 'present' if enable_yoda_report else 'absent' }}"
