---
# copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


- name: Ensure iRODS consistency check virtualenv exists
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.command: "{{ irods_consistency_check_python3_path }} -m venv /var/lib/irods/irods-consistency-check"
  args:
    creates: /var/lib/irods/irods-consistency-check


- name: Ensure iRODS consistency check is installed
  become_user: '{{ irods_service_account }}'
  become: true
  ansible.builtin.pip:
    name: "git+https://github.com/UtrechtUniversity/irods-consistency-check.git@v{{ irods_consistency_check_version }}"
    virtualenv: '/var/lib/irods/irods-consistency-check'
    virtualenv_python: python3
