---
# copyright Utrecht University

zabbix_agent2_postgresql_plugin:
  package: zabbix-agent2-plugin-postgresql
  package_version: 7.4.5
  url: https://repo.zabbix.com/zabbix/7.4/stable/ubuntu/pool/main/z/zabbix-agent2-plugin-postgresql/
  filename: zabbix-agent2-plugin-postgresql_7.4.5-1%2Bubuntu24.04_amd64.deb
  checksum: sha256:a72f8987ae7d21b492fbc229fa2771807a04e85746b80735a1ad576c6e621d4e
