---
# copyright Utrecht University

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"


- name: Check if systemd service is active for handler
  # noqa command-instead-of-module
  ansible.builtin.command: "systemctl is-active irods"
  register: irods_runtime_irods_service_status
  ignore_errors: true
  changed_when: false


- name: Ensure iRODS runtime is installed
  ansible.builtin.package:
    name: "{{ irods_runtime_package_new }}"
    state: present


- name: Ensure iRODS runtime is pinned
  ansible.builtin.template:
    src: 'irods_runtime.pref.j2'
    dest: '/etc/apt/preferences.d/irods_runtime.pref'
    mode: '0644'
    owner: 'root'
    group: 'root'
  when: ansible_os_family == 'Debian'


- name: Ensure iRODS runtime version is locked
  community.general.dnf_versionlock:
    name: "{{ irods_runtime_package_new }}"
    state: present
  when: ansible_os_family == 'RedHat'
