---
# copyright Utrecht University

- name: Ensure Ansible dependencies are installed (EL8)
  ansible.builtin.package:
    name:
      - python3-libselinux
      - python3-libsemanage
      - python3-policycoreutils
      - python3-dnf-plugin-versionlock
    state: present
  when: ansible_distribution_major_version == "8"


- name: Ensure Ansible dependencies are installed (EL9)
  ansible.builtin.package:
    name:
      - python3-libselinux
      - python3-libsemanage
      - python3-policycoreutils
      - python3-dnf-plugin-versionlock
    state: present
  when: ansible_distribution_major_version == "9"


- name: Ensure basics (vim, bind-utils, etc.) are installed
  ansible.builtin.package:
    name:
      - bind-utils
      - vim
      - htop
      - git
      - tmux
      - rsync
      - jq
      - curl
    state: present


- name: Gather package facts
  ansible.builtin.package_facts:
    manager: rpm
