---
# copyright Utrecht University

- name: Ensure unattended-upgrades service has been stopped and disabled
  ansible.builtin.service:
    name: unattended-upgrades
    state: stopped
    enabled: false
  when: "'unattended-upgrades' in ansible_facts.packages"


- name: Disable automatic unattended upgrades
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '^\s*APT::Periodic::Unattended-Upgrade\s+'
    line: 'APT::Periodic::Unattended-Upgrade "0";'
  when: "'unattended-upgrades' in ansible_facts.packages"
