---
# copyright Utrecht University

- name: Run common tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_common_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that common role has run
  ansible.builtin.set_fact:
    yoda_common_role_has_run: true
  when: '"yoda_common_role_has_run" not in hostvars[inventory_hostname]'
