---
# copyright Utrecht University

- name: Run apache_wsgi tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_apache_wsgi_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that apache_wsgi role has run
  ansible.builtin.set_fact:
    yoda_apache_wsgi_role_has_run: true
  when: '"yoda_apache_wsgi_role_has_run" not in hostvars[inventory_hostname]'
