---
# copyright Utrecht University

- name: Install Mod-WSGI for Python (Ubuntu)
  ansible.builtin.apt:
    name: libapache2-mod-wsgi-py3
  when: ansible_os_family == 'Debian'


- name: Install Mod-WSGI for Python (EL)
  ansible.builtin.pip:
    name:
      - mod-wsgi==5.0.2
    executable: /usr/bin/pip3.12
  when: ansible_os_family == 'RedHat'


- name: Configure WSGI module in Apache
  ansible.builtin.copy:
    src: 02-wsgi.conf
    dest: /etc/httpd/conf.modules.d/02-wsgi.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache webserver
  when: ansible_os_family == 'RedHat'


- name: Remove old WSGI configurations in Apache
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  notify: Restart Apache webserver
  when: ansible_os_family == 'RedHat'
  with_items:
    - /etc/httpd/conf.modules.d/10-wsgi.conf
    - /etc/httpd/conf.modules.d/10-wsgi-python3.conf


- name: Upload custom SELinux module for WSGI with Python
  ansible.builtin.copy:
    src: my-httpd.pp
    dest: /root/my-httpd.pp
    owner: root
    group: root
    mode: '0644'
  register: python_selinux
  when: ansible_os_family == 'RedHat'


# Running as task instead of handler in order to prevent ordering issues
# with Apache restart handler.
- name: Apply SELinux policy # noqa no-handler
  ansible.builtin.command:
    cmd: semodule -i /root/my-httpd.pp
  changed_when: false
  when: ansible_os_family == 'RedHat' and not ansible_check_mode and python_selinux.changed
