---
# copyright Utrecht University

- name: Run irods_ubuntu_dependencies tasks if role has not run yet
  ansible.builtin.include_tasks: main-tasks.yml
  when: '"yoda_irods_ubuntu_dependencies_role_has_run" not in hostvars[inventory_hostname]'

- name: Register that irods_ubuntu_dependencies role has run
  ansible.builtin.set_fact:
    yoda_irods_ubuntu_dependencies_role_has_run: true
  when: '"yoda_irods_ubuntu_dependencies_role_has_run" not in hostvars[inventory_hostname]'
