---
# copyright Utrecht University

# iRODS configuration.
irods_admin: rods                          # iRODS admin username
irods_password: rods                       # iRODS admin password
irods_icat_fqdn: icat.yoda.test
irods_authentication_scheme: pam_password  # iRODS authentication method: "native" or "pam_password"
irods_zone: tempZone                       # The name of the iRODS Zone
irods_default_resc: irodsResc              # iRODS default resource name
irods_port_range_begin: 20000
irods_port_range_end: 20199
irods_icat_port: 1247
irods_service_account: irods
irods_vault_directory: /var/lib/irods/Vault
irods_control_plane_port: 1248
irods_schema_uri: /var/lib/irods/configuration_schemas
irods_ssl_verify_server: cert

irods_resource_caching_settings:
  advanced_settings/dns_cache/eviction_age_in_seconds: 3600
  advanced_settings/dns_cache/shared_memory_size_in_bytes: 5000000
  advanced_settings/hostname_cache/eviction_age_in_seconds: 3600
  advanced_settings/hostname_cache/shared_memory_size_in_bytes: 2500000

# OpenSSL configuration
openssl_dhparams: dhparams.pem
openssl_key_signed: localhost.key
openssl_crt_signed_and_chain: localhost_and_chain.crt

# Whether to start iRODS at boot time.
irods_enable_service: true

irods_max_open_files: 131072
