---
# copyright Utrecht University

- name: Ensure NFS utilities are installed (Debian)
  ansible.builtin.package:
    name: nfs-common
    state: present
  when: ansible_os_family == 'Debian'


- name: Ensure NFS utilities are installed (RedHat)
  ansible.builtin.package:
    name: nfs-utils
    state: present
  when: ansible_os_family == 'RedHat'


- name: Ensure NFS mount points exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: irods
    group: irods
    mode: '0755'
  loop: "{{ nfs_mounts if nfs_mounts is iterable else [] }}"
  when: item.host == ansible_fqdn


- name: Ensure NFS shares are mounted and present in /etc/fstab
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs
    opts: rw,sync,hard,intr
    state: mounted
    dump: 0
    passno: 0
  loop: "{{ nfs_mounts if nfs_mounts is iterable else [] }}"
  when: item.host == ansible_fqdn


- name: Ensure systemd unit file to mount NFS volumes is present
  ansible.builtin.template:
    src: mount-nfs-volumes.service.j2
    dest: /etc/systemd/system/mount-nfs-volumes.service
    owner: root
    group: root
    mode: '0644'
  notify: Systemd daemon reload


- name: Enable or disable service to mount NFS volumes
  ansible.builtin.service:
    name: mount-nfs-volumes
    state: '{{ "started" if nfs_client_mount_volumes_on_boot else "stopped" }}'
    enabled: '{{ nfs_client_mount_volumes_on_boot }}'
  when: not ansible_check_mode
