---
# copyright Utrecht University

irods_microservices_data:
  irods_sudo_microservices:
    package: irods-sudo-microservices
    version: 5.0.2-1.0.0-1
    url: https://github.com/UtrechtUniversity/irods-sudo-microservices/releases/download/5.0.2_1.0.0/irods-sudo-microservices-5.0.2-1.0.0-1.deb
    filename: irods-sudo-microservices-5.0.2-1.0.0-1.deb
    checksum: sha256:1afd4747a36f3f05f2246a7e4359ae002007da14f82e30fa384c363f2c4577e7
  irods_uu_microservices:
    package: irods-uu-microservices
    version: 5.0.2-1.3.1-0
    url: https://github.com/UtrechtUniversity/irods-uu-microservices/releases/download/v1.3.1/irods-uu-microservices-5.0.2-1.3.1-0.deb
    filename: irods-uu-microservices-5.0.2-1.3.1-0.deb
    checksum: sha256:a9048d6f4bea8c6815ae0b9e74c1196427dcbafa7c222caf3f7ff2a02f1afeee
