---
# copyright Utrecht University

irods_microservices_data:
  irods_sudo_microservices:
    package: irods-sudo-microservices
    version: 4.3.3-1.0.0-1
    url: https://github.com/UtrechtUniversity/irods-sudo-microservices/releases/download/4.3.3_1.0.0/irods-sudo-microservices-4.3.3-1.0.0-1.deb
    filename: irods-sudo-microservices-4.3.3-1.0.0-1.deb
    checksum: sha256:039ccbb892590208b88c800b8a197cc5e75bd40ac9304edf019f9fc527ead22c
  irods_uu_microservices:
    package: irods-uu-microservices
    version: 4.3.3-1.2.0-0
    url: https://github.com/UtrechtUniversity/irods-uu-microservices/releases/download/v1.2.0/irods-uu-microservices-4.3.3-1.2.0-0.deb
    filename: irods-uu-microservices-4.3.3-1.2.0-0.deb
    checksum: sha256:beaaa5171e9068f55fc81662057d578b03e56e938b438c739ac7f962ec56b868
