---
# copyright Utrecht University

irods_microservices_data:
  irods_sudo_microservices:
    package: irods-sudo-microservices
    version: 4.3.3-1.0.0-1
    url: https://github.com/UtrechtUniversity/irods-sudo-microservices/releases/download/4.3.3_1.0.0/irods-sudo-microservices-4.3.3_1.0.0-1.rpm
    filename: irods-sudo-microservices-4.3.3-1.0.0-1.rpm
    checksum: sha256:fdaf51d0e6b70422c7f79433096489c2305eea053e0afc9dd88fe1b22d4b969b
  irods_uu_microservices:
    package: irods-uu-microservices
    version: 4.3.3-1.2.0-0
    url: https://github.com/UtrechtUniversity/irods-uu-microservices/releases/download/v1.2.0/irods-uu-microservices-4.3.3_1.2.0-0.rpm
    filename: irods-uu-microservices-4.3.3-1.2.0-0.rpm
    checksum: sha256:888e1d2dded9c010328324025fb38523ddafddb4e3884bd4cec21453f9e32261
