---
# copyright Utrecht University

irods_microservices_data:
  irods_sudo_microservices:
    package: irods-sudo-microservices
    version: 4.3.4-1.0.0-1
    url: https://github.com/UtrechtUniversity/irods-sudo-microservices/releases/download/4.3.4_1.0.0/irods-sudo-microservices-4.3.4_1.0.0-1.rpm
    filename: irods-sudo-microservices-4.3.4-1.0.0-1.rpm
    checksum: sha256:6035d75c4d5b719220803ef63007fa5dc7fc550fcd0fbbab205f95573b17eeff
  irods_uu_microservices:
    package: irods-uu-microservices
    version: 4.3.4-1.2.0-0
    url: https://github.com/UtrechtUniversity/irods-uu-microservices/releases/download/v1.2.1/irods-uu-microservices-4.3.4_1.2.1-0.rpm
    filename: irods-uu-microservices-4.3.4-1.2.1-0.rpm
    checksum: sha256:77ec3a4a8da73491b63936f4537f5c42f57c5b5bc548f5f966f8bfe9d12f2bc1
