---
# copyright Utrecht University

- name: Download DavRODS package
  ansible.builtin.get_url:
    url: "{{ yoda_davrods_url }}"
    dest: "/tmp/davrods-{{ yoda_davrods_version }}.rpm"
    checksum: '{{ yoda_davrods_checksum }}'
    mode: "0644"


- name: Install DavRODS
  ansible.builtin.dnf:
    name: "/tmp/davrods-{{ yoda_davrods_version }}.rpm"
    disable_gpg_check: true
    state: present
  notify: Restart Apache webserver
