---
# copyright Utrecht University

# Temporary directory to store downloaded rpm files.
rpm_dest_dir: /tmp

# Zabbix postgres database user (CREATE ROLE zabbix WITH LOGIN NOSUPERUSER, NOCREATEDB, NOCREATEROLE
# and (GRANT CONNECT ON DATABASE "ICAT" TO zabbix)
# Zabbix configuration
zabbix_database_user: zabbix
zabbix_database_user_password: PLACEHOLDER

repo_only: false # Only download packages from repos.
