name: Lint Dockerfiles

on:
  pull_request:
    paths:
    - 'docker/images/davrods/Dockerfile'
    - 'docker/images/yoda_eus/Dockerfile'
    - 'docker/images/yoda_irods_icat/Dockerfile'
    - 'docker/images/yoda_portal/Dockerfile'
    - 'docker/images/yoda_public/Dockerfile'
    - 'docker/images/yoda_web_mock/Dockerfile'
  push:
    paths:
    - 'docker/images/davrods/Dockerfile'
    - 'docker/images/yoda_eus/Dockerfile'
    - 'docker/images/yoda_irods_icat/Dockerfile'
    - 'docker/images/yoda_portal/Dockerfile'
    - 'docker/images/yoda_public/Dockerfile'
    - 'docker/images/yoda_web_mock/Dockerfile'

jobs:
  build:
   runs-on: ubuntu-22.04
   steps:
   - uses: actions/checkout@v6
   - uses: jbergstroem/hadolint-gh-action@v1
     with:
       config_file: docker/hadolint.yml
       dockerfile: docker/images/**/Dockerfile
